// Builds the FULL Magic: The Gathering catalogue from Scryfall's bulk data.
// Run where api.scryfall.com / data.scryfall.io are reachable (locally, CI, or
// once the hosts are on the environment's network-egress allowlist):
//   node prisma/fetch-mtg.mjs
//
// Emits prisma/mtg-cards.json (every English paper printing, with real Scryfall
// image URLs) and rewrites src/lib/pokemon-sets.ts with the derived set list.
// Then: npx prisma db push && npx tsx prisma/seed.ts
import { writeFileSync, existsSync, statSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { execSync } from "node:child_process";

const TMP = "/tmp/scryfall-default-cards.json";

async function main() {
  if (!existsSync(TMP) || statSync(TMP).size < 1_000_000) {
    console.log("Resolving Scryfall bulk-data download URI…");
    const meta = JSON.parse(execSync(`curl -s -L -m 60 "https://api.scryfall.com/bulk-data"`).toString());
    const entry = meta.data.find((d) => d.type === "default_cards");
    if (!entry) throw new Error("default_cards bulk entry not found");
    console.log(`Downloading ${entry.download_uri} (~500MB)…`);
    execSync(`curl -s -L -m 900 -o ${TMP} "${entry.download_uri}"`, { stdio: "inherit" });
  }
  console.log("Parsing bulk file…");
  const all = JSON.parse(readFileSync(TMP, "utf8"));
  console.log(`Parsed ${all.length} Scryfall objects.`);

  const COLOR = { W: "White", U: "Blue", B: "Black", R: "Red", G: "Green" };
  const slugify = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60);
  function domainOf(c) {
    const cols = c.colors ?? c.card_faces?.[0]?.colors ?? [];
    if ((c.type_line || "").includes("Land")) return "Land";
    if (cols.length === 0) return "Colorless";
    if (cols.length > 1) return "Multicolor";
    return COLOR[cols[0]] ?? "Colorless";
  }
  function typeOf(c) {
    const t = c.type_line || "";
    for (const f of ["Planeswalker", "Creature", "Instant", "Sorcery", "Enchantment", "Artifact", "Battle", "Land"]) if (t.includes(f)) return f;
    return "Card";
  }
  const RAR = { common: "Common", uncommon: "Uncommon", rare: "Rare", mythic: "Mythic", special: "Special", bonus: "Special" };
  function imageOf(c) {
    return c.image_uris?.normal ?? c.card_faces?.[0]?.image_uris?.normal ?? null;
  }

  const out = [];
  const setMap = new Map();
  for (const c of all) {
    if (c.lang !== "en") continue;
    if (c.digital) continue;
    if (!(c.games || []).includes("paper")) continue;
    if (["token", "double_faced_token", "emblem", "art_series", "memorabilia"].includes(c.layout)) continue;
    const img = imageOf(c);
    if (!img) continue;
    const setCode = (c.set || "").toUpperCase();
    if (!setMap.has(setCode)) setMap.set(setCode, { name: c.set_name, date: c.released_at || "2000/01/01", count: 0 });
    setMap.get(setCode).count++;
    out.push({
      externalId: c.id,
      name: c.name,
      setCode,
      setName: c.set_name,
      releaseDate: (c.released_at || "2000-01-01").replace(/-/g, "/"),
      collectorNumber: `${c.collector_number}`,
      number: `${c.collector_number}`,
      domain: domainOf(c),
      type: typeOf(c),
      subtype: c.type_line || null,
      rarity: RAR[c.rarity] || "Rare",
      hp: null,
      artist: c.artist || null,
      flavorText: c.flavor_text || null,
      imageUrl: img,
      imageThumbUrl: c.image_uris?.small ?? img,
    });
  }
  console.log(`Built ${out.length} cards across ${setMap.size} sets.`);
  writeFileSync(join(process.cwd(), "prisma", "mtg-cards.json"), JSON.stringify(out));

  const sets = [...setMap.entries()].map(([code, v]) => ({
    code, name: v.name, slug: slugify(v.name) || code.toLowerCase(), series: "Magic",
    releaseDate: (v.date || "2000-01-01").replace(/-/g, "/"), total: v.count, logo: null, symbol: null,
  }));
  const seen = {};
  for (const s of sets) { if (seen[s.slug]) s.slug = `${s.slug}-${s.code.toLowerCase()}`; seen[s.slug] = 1; }
  sets.sort((a, b) => (a.releaseDate < b.releaseDate ? 1 : a.releaseDate > b.releaseDate ? -1 : a.name.localeCompare(b.name)));
  const ts = `// AUTO-GENERATED by prisma/fetch-mtg.mjs from Scryfall bulk data. Do not edit by hand.
export interface PokemonSet { code: string; name: string; slug: string; series: string; releaseDate: string; total: number; logo: string | null; symbol: string | null; }
export const POKEMON_SETS: PokemonSet[] = ${JSON.stringify(sets)};
`;
  writeFileSync(join(process.cwd(), "src", "lib", "pokemon-sets.ts"), ts);
  console.log(`Wrote ${sets.length} sets to src/lib/pokemon-sets.ts`);
}
main().catch((e) => { console.error(e); process.exit(1); });
