// AUTO-GENERATED by scripts/build-pokemon-data.ts — do not edit by hand.
// The full Pokémon TCG set catalogue (173 sets), newest first.
export interface PokemonSet {
  code: string;
  name: string;
  slug: string;
  series: string;
  releaseDate: string;
  total: number;
  logo: string | null;
  symbol: string | null;
}
export const POKEMON_SETS: PokemonSet[] = [
  {
    "code": "me4",
    "name": "Chaos Rising",
    "slug": "chaos-rising",
    "series": "Mega Evolution",
    "releaseDate": "2026/05/22",
    "total": 86,
    "logo": "https://images.scrydex.com/pokemon/me4-logo/logo",
    "symbol": "https://images.scrydex.com/pokemon/me4-symbol/symbol"
  },
  {
    "code": "me3",
    "name": "Perfect Order",
    "slug": "perfect-order",
    "series": "Mega Evolution",
    "releaseDate": "2026/03/27",
    "total": 88,
    "logo": "https://images.scrydex.com/pokemon/me3-logo/logo",
    "symbol": "https://images.scrydex.com/pokemon/me3-symbol/symbol"
  },
  {
    "code": "me2pt5",
    "name": "Ascended Heroes",
    "slug": "ascended-heroes",
    "series": "Mega Evolution",
    "releaseDate": "2026/01/30",
    "total": 217,
    "logo": "https://images.scrydex.com/pokemon/me2pt5-logo/logo",
    "symbol": "https://images.scrydex.com/pokemon/me2pt5-symbol/symbol"
  },
  {
    "code": "me2",
    "name": "Phantasmal Flames",
    "slug": "phantasmal-flames",
    "series": "Mega Evolution",
    "releaseDate": "2025/11/14",
    "total": 94,
    "logo": "https://images.pokemontcg.io/me2/logo.png",
    "symbol": "https://images.pokemontcg.io/me2/symbol.png"
  },
  {
    "code": "me1",
    "name": "Mega Evolution",
    "slug": "mega-evolution",
    "series": "Mega Evolution",
    "releaseDate": "2025/09/26",
    "total": 132,
    "logo": "https://images.pokemontcg.io/me1/logo.png",
    "symbol": "https://images.pokemontcg.io/me1/symbol.png"
  },
  {
    "code": "zsv10pt5",
    "name": "Black Bolt",
    "slug": "black-bolt",
    "series": "Scarlet & Violet",
    "releaseDate": "2025/07/18",
    "total": 86,
    "logo": "https://images.pokemontcg.io/zsv10pt5/logo.png",
    "symbol": "https://images.pokemontcg.io/zsv10pt5/symbol.png"
  },
  {
    "code": "rsv10pt5",
    "name": "White Flare",
    "slug": "white-flare",
    "series": "Scarlet & Violet",
    "releaseDate": "2025/07/18",
    "total": 86,
    "logo": "https://images.pokemontcg.io/rsv10pt5/logo.png",
    "symbol": "https://images.pokemontcg.io/rsv10pt5/symbol.png"
  },
  {
    "code": "sv10",
    "name": "Destined Rivals",
    "slug": "destined-rivals",
    "series": "Scarlet & Violet",
    "releaseDate": "2025/05/30",
    "total": 182,
    "logo": "https://images.pokemontcg.io/sv10/logo.png",
    "symbol": "https://images.pokemontcg.io/sv10/symbol.png"
  },
  {
    "code": "sv9",
    "name": "Journey Together",
    "slug": "journey-together",
    "series": "Scarlet & Violet",
    "releaseDate": "2025/03/28",
    "total": 159,
    "logo": "https://images.pokemontcg.io/sv9/logo.png",
    "symbol": "https://images.pokemontcg.io/sv9/symbol.png"
  },
  {
    "code": "sv8pt5",
    "name": "Prismatic Evolutions",
    "slug": "prismatic-evolutions",
    "series": "Scarlet & Violet",
    "releaseDate": "2025/01/17",
    "total": 131,
    "logo": "https://images.pokemontcg.io/sv8pt5/logo.png",
    "symbol": "https://images.pokemontcg.io/sv8pt5/symbol.png"
  },
  {
    "code": "sv8",
    "name": "Surging Sparks",
    "slug": "surging-sparks",
    "series": "Scarlet & Violet",
    "releaseDate": "2024/11/08",
    "total": 191,
    "logo": "https://images.pokemontcg.io/sv8/logo.png",
    "symbol": "https://images.pokemontcg.io/sv8/symbol.png"
  },
  {
    "code": "sv7",
    "name": "Stellar Crown",
    "slug": "stellar-crown",
    "series": "Scarlet & Violet",
    "releaseDate": "2024/09/13",
    "total": 142,
    "logo": "https://images.pokemontcg.io/sv7/logo.png",
    "symbol": "https://images.pokemontcg.io/sv7/symbol.png"
  },
  {
    "code": "sv6pt5",
    "name": "Shrouded Fable",
    "slug": "shrouded-fable",
    "series": "Scarlet & Violet",
    "releaseDate": "2024/08/02",
    "total": 64,
    "logo": "https://images.pokemontcg.io/sv6pt5/logo.png",
    "symbol": "https://images.pokemontcg.io/sv6pt5/symbol.png"
  },
  {
    "code": "sv6",
    "name": "Twilight Masquerade",
    "slug": "twilight-masquerade",
    "series": "Scarlet & Violet",
    "releaseDate": "2024/05/24",
    "total": 167,
    "logo": "https://images.pokemontcg.io/sv6/logo.png",
    "symbol": "https://images.pokemontcg.io/sv6/symbol.png"
  },
  {
    "code": "sv5",
    "name": "Temporal Forces",
    "slug": "temporal-forces",
    "series": "Scarlet & Violet",
    "releaseDate": "2024/03/22",
    "total": 162,
    "logo": "https://images.pokemontcg.io/sv5/logo.png",
    "symbol": "https://images.pokemontcg.io/sv5/symbol.png"
  },
  {
    "code": "sv4pt5",
    "name": "Paldean Fates",
    "slug": "paldean-fates",
    "series": "Scarlet & Violet",
    "releaseDate": "2024/01/26",
    "total": 91,
    "logo": "https://images.pokemontcg.io/sv4pt5/logo.png",
    "symbol": "https://images.pokemontcg.io/sv4pt5/symbol.png"
  },
  {
    "code": "sv4",
    "name": "Paradox Rift",
    "slug": "paradox-rift",
    "series": "Scarlet & Violet",
    "releaseDate": "2023/11/03",
    "total": 182,
    "logo": "https://images.pokemontcg.io/sv4/logo.png",
    "symbol": "https://images.pokemontcg.io/sv4/symbol.png"
  },
  {
    "code": "sv3pt5",
    "name": "151",
    "slug": "151",
    "series": "Scarlet & Violet",
    "releaseDate": "2023/09/22",
    "total": 165,
    "logo": "https://images.pokemontcg.io/sv3pt5/logo.png",
    "symbol": "https://images.pokemontcg.io/sv3pt5/symbol.png"
  },
  {
    "code": "sv3",
    "name": "Obsidian Flames",
    "slug": "obsidian-flames",
    "series": "Scarlet & Violet",
    "releaseDate": "2023/08/11",
    "total": 197,
    "logo": "https://images.pokemontcg.io/sv3/logo.png",
    "symbol": "https://images.pokemontcg.io/sv3/symbol.png"
  },
  {
    "code": "sv2",
    "name": "Paldea Evolved",
    "slug": "paldea-evolved",
    "series": "Scarlet & Violet",
    "releaseDate": "2023/06/09",
    "total": 193,
    "logo": "https://images.pokemontcg.io/sv2/logo.png",
    "symbol": "https://images.pokemontcg.io/sv2/symbol.png"
  },
  {
    "code": "sve",
    "name": "Scarlet & Violet Energies",
    "slug": "scarlet-violet-energies",
    "series": "Scarlet & Violet",
    "releaseDate": "2023/03/31",
    "total": 8,
    "logo": "https://images.pokemontcg.io/sve/logo.png",
    "symbol": "https://images.pokemontcg.io/sve/symbol.png"
  },
  {
    "code": "sv1",
    "name": "Scarlet & Violet",
    "slug": "scarlet-violet",
    "series": "Scarlet & Violet",
    "releaseDate": "2023/03/31",
    "total": 198,
    "logo": "https://images.pokemontcg.io/sv1/logo.png",
    "symbol": "https://images.pokemontcg.io/sv1/symbol.png"
  },
  {
    "code": "swsh12pt5",
    "name": "Crown Zenith",
    "slug": "crown-zenith",
    "series": "Sword & Shield",
    "releaseDate": "2023/01/20",
    "total": 159,
    "logo": "https://images.pokemontcg.io/swsh12pt5/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh12pt5/symbol.png"
  },
  {
    "code": "swsh12pt5gg",
    "name": "Crown Zenith Galarian Gallery",
    "slug": "crown-zenith-galarian-gallery",
    "series": "Sword & Shield",
    "releaseDate": "2023/01/20",
    "total": 70,
    "logo": "https://images.pokemontcg.io/swsh12pt5gg/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh12pt5gg/symbol.png"
  },
  {
    "code": "svp",
    "name": "Scarlet & Violet Black Star Promos",
    "slug": "scarlet-violet-black-star-promos",
    "series": "Scarlet & Violet",
    "releaseDate": "2023/01/01",
    "total": 102,
    "logo": "https://images.pokemontcg.io/svp/logo.png",
    "symbol": "https://images.pokemontcg.io/svp/symbol.png"
  },
  {
    "code": "swsh12",
    "name": "Silver Tempest",
    "slug": "silver-tempest",
    "series": "Sword & Shield",
    "releaseDate": "2022/11/11",
    "total": 195,
    "logo": "https://images.pokemontcg.io/swsh12/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh12/symbol.png"
  },
  {
    "code": "swsh12tg",
    "name": "Silver Tempest Trainer Gallery",
    "slug": "silver-tempest-trainer-gallery",
    "series": "Sword & Shield",
    "releaseDate": "2022/11/11",
    "total": 30,
    "logo": "https://images.pokemontcg.io/swsh12tg/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh12tg/symbol.png"
  },
  {
    "code": "swsh11",
    "name": "Lost Origin",
    "slug": "lost-origin",
    "series": "Sword & Shield",
    "releaseDate": "2022/09/09",
    "total": 196,
    "logo": "https://images.pokemontcg.io/swsh11/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh11/symbol.png"
  },
  {
    "code": "swsh11tg",
    "name": "Lost Origin Trainer Gallery",
    "slug": "lost-origin-trainer-gallery",
    "series": "Sword & Shield",
    "releaseDate": "2022/09/09",
    "total": 30,
    "logo": "https://images.pokemontcg.io/swsh11tg/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh11tg/symbol.png"
  },
  {
    "code": "mcd22",
    "name": "McDonald's Collection 2022",
    "slug": "mcdonald-s-collection-2022",
    "series": "Other",
    "releaseDate": "2022/08/03",
    "total": 15,
    "logo": "https://images.pokemontcg.io/mcd22/logo.png",
    "symbol": "https://images.pokemontcg.io/mcd22/symbol.png"
  },
  {
    "code": "pgo",
    "name": "Pokémon GO",
    "slug": "pok-mon-go",
    "series": "Sword & Shield",
    "releaseDate": "2022/07/01",
    "total": 78,
    "logo": "https://images.pokemontcg.io/pgo/logo.png",
    "symbol": "https://images.pokemontcg.io/pgo/symbol.png"
  },
  {
    "code": "swsh10",
    "name": "Astral Radiance",
    "slug": "astral-radiance",
    "series": "Sword & Shield",
    "releaseDate": "2022/05/27",
    "total": 189,
    "logo": "https://images.pokemontcg.io/swsh10/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh10/symbol.png"
  },
  {
    "code": "swsh10tg",
    "name": "Astral Radiance Trainer Gallery",
    "slug": "astral-radiance-trainer-gallery",
    "series": "Sword & Shield",
    "releaseDate": "2022/05/27",
    "total": 30,
    "logo": "https://images.pokemontcg.io/swsh10tg/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh10tg/symbol.png"
  },
  {
    "code": "swsh9",
    "name": "Brilliant Stars",
    "slug": "brilliant-stars",
    "series": "Sword & Shield",
    "releaseDate": "2022/02/25",
    "total": 172,
    "logo": "https://images.pokemontcg.io/swsh9/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh9/symbol.png"
  },
  {
    "code": "swsh9tg",
    "name": "Brilliant Stars Trainer Gallery",
    "slug": "brilliant-stars-trainer-gallery",
    "series": "Sword & Shield",
    "releaseDate": "2022/02/25",
    "total": 30,
    "logo": "https://images.pokemontcg.io/swsh9tg/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh9tg/symbol.png"
  },
  {
    "code": "swsh8",
    "name": "Fusion Strike",
    "slug": "fusion-strike",
    "series": "Sword & Shield",
    "releaseDate": "2021/11/12",
    "total": 264,
    "logo": "https://images.pokemontcg.io/swsh8/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh8/symbol.png"
  },
  {
    "code": "cel25",
    "name": "Celebrations",
    "slug": "celebrations",
    "series": "Sword & Shield",
    "releaseDate": "2021/10/08",
    "total": 25,
    "logo": "https://images.pokemontcg.io/cel25/logo.png",
    "symbol": "https://images.pokemontcg.io/cel25/symbol.png"
  },
  {
    "code": "cel25c",
    "name": "Celebrations: Classic Collection",
    "slug": "celebrations-classic-collection",
    "series": "Sword & Shield",
    "releaseDate": "2021/10/08",
    "total": 25,
    "logo": "https://images.pokemontcg.io/cel25c/logo.png",
    "symbol": "https://images.pokemontcg.io/cel25c/symbol.png"
  },
  {
    "code": "swsh7",
    "name": "Evolving Skies",
    "slug": "evolving-skies",
    "series": "Sword & Shield",
    "releaseDate": "2021/08/27",
    "total": 203,
    "logo": "https://images.pokemontcg.io/swsh7/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh7/symbol.png"
  },
  {
    "code": "swsh6",
    "name": "Chilling Reign",
    "slug": "chilling-reign",
    "series": "Sword & Shield",
    "releaseDate": "2021/06/18",
    "total": 198,
    "logo": "https://images.pokemontcg.io/swsh6/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh6/symbol.png"
  },
  {
    "code": "swsh5",
    "name": "Battle Styles",
    "slug": "battle-styles",
    "series": "Sword & Shield",
    "releaseDate": "2021/03/19",
    "total": 163,
    "logo": "https://images.pokemontcg.io/swsh5/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh5/symbol.png"
  },
  {
    "code": "swsh45",
    "name": "Shining Fates",
    "slug": "shining-fates",
    "series": "Sword & Shield",
    "releaseDate": "2021/02/19",
    "total": 72,
    "logo": "https://images.pokemontcg.io/swsh45/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh45/symbol.png"
  },
  {
    "code": "swsh45sv",
    "name": "Shining Fates Shiny Vault",
    "slug": "shining-fates-shiny-vault",
    "series": "Sword & Shield",
    "releaseDate": "2021/02/19",
    "total": 122,
    "logo": "https://images.pokemontcg.io/swsh45sv/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh45sv/symbol.png"
  },
  {
    "code": "mcd21",
    "name": "McDonald's Collection 2021",
    "slug": "mcdonald-s-collection-2021",
    "series": "Other",
    "releaseDate": "2021/02/09",
    "total": 25,
    "logo": "https://images.pokemontcg.io/mcd21/logo.png",
    "symbol": "https://images.pokemontcg.io/mcd21/symbol.png"
  },
  {
    "code": "swsh4",
    "name": "Vivid Voltage",
    "slug": "vivid-voltage",
    "series": "Sword & Shield",
    "releaseDate": "2020/11/13",
    "total": 185,
    "logo": "https://images.pokemontcg.io/swsh4/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh4/symbol.png"
  },
  {
    "code": "swsh35",
    "name": "Champion's Path",
    "slug": "champion-s-path",
    "series": "Sword & Shield",
    "releaseDate": "2020/09/25",
    "total": 73,
    "logo": "https://images.pokemontcg.io/swsh35/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh35/symbol.png"
  },
  {
    "code": "fut20",
    "name": "Pokémon Futsal Collection",
    "slug": "pok-mon-futsal-collection",
    "series": "Other",
    "releaseDate": "2020/09/11",
    "total": 5,
    "logo": "https://images.pokemontcg.io/fut20/logo.png",
    "symbol": "https://images.pokemontcg.io/fut20/symbol.png"
  },
  {
    "code": "swsh3",
    "name": "Darkness Ablaze",
    "slug": "darkness-ablaze",
    "series": "Sword & Shield",
    "releaseDate": "2020/08/14",
    "total": 189,
    "logo": "https://images.pokemontcg.io/swsh3/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh3/symbol.png"
  },
  {
    "code": "swsh2",
    "name": "Rebel Clash",
    "slug": "rebel-clash",
    "series": "Sword & Shield",
    "releaseDate": "2020/05/01",
    "total": 192,
    "logo": "https://images.pokemontcg.io/swsh2/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh2/symbol.png"
  },
  {
    "code": "swsh1",
    "name": "Sword & Shield",
    "slug": "sword-shield",
    "series": "Sword & Shield",
    "releaseDate": "2020/02/07",
    "total": 202,
    "logo": "https://images.pokemontcg.io/swsh1/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh1/symbol.png"
  },
  {
    "code": "swshp",
    "name": "SWSH Black Star Promos",
    "slug": "swsh-black-star-promos",
    "series": "Sword & Shield",
    "releaseDate": "2019/11/15",
    "total": 307,
    "logo": "https://images.pokemontcg.io/swshp/logo.png",
    "symbol": "https://images.pokemontcg.io/swshp/symbol.png"
  },
  {
    "code": "sm12",
    "name": "Cosmic Eclipse",
    "slug": "cosmic-eclipse",
    "series": "Sun & Moon",
    "releaseDate": "2019/11/01",
    "total": 236,
    "logo": "https://images.pokemontcg.io/sm12/logo.png",
    "symbol": "https://images.pokemontcg.io/sm12/symbol.png"
  },
  {
    "code": "mcd19",
    "name": "McDonald's Collection 2019",
    "slug": "mcdonald-s-collection-2019",
    "series": "Other",
    "releaseDate": "2019/10/15",
    "total": 12,
    "logo": "https://images.pokemontcg.io/mcd19/logo.png",
    "symbol": "https://images.pokemontcg.io/mcd19/symbol.png"
  },
  {
    "code": "sm115",
    "name": "Hidden Fates",
    "slug": "hidden-fates",
    "series": "Sun & Moon",
    "releaseDate": "2019/08/23",
    "total": 68,
    "logo": "https://images.pokemontcg.io/sm115/logo.png",
    "symbol": "https://images.pokemontcg.io/sm115/symbol.png"
  },
  {
    "code": "sma",
    "name": "Hidden Fates Shiny Vault",
    "slug": "hidden-fates-shiny-vault",
    "series": "Sun & Moon",
    "releaseDate": "2019/08/23",
    "total": 94,
    "logo": "https://images.pokemontcg.io/sma/logo.png",
    "symbol": "https://images.pokemontcg.io/sma/symbol.png"
  },
  {
    "code": "sm11",
    "name": "Unified Minds",
    "slug": "unified-minds",
    "series": "Sun & Moon",
    "releaseDate": "2019/08/02",
    "total": 236,
    "logo": "https://images.pokemontcg.io/sm11/logo.png",
    "symbol": "https://images.pokemontcg.io/sm11/symbol.png"
  },
  {
    "code": "sm10",
    "name": "Unbroken Bonds",
    "slug": "unbroken-bonds",
    "series": "Sun & Moon",
    "releaseDate": "2019/05/03",
    "total": 214,
    "logo": "https://images.pokemontcg.io/sm10/logo.png",
    "symbol": "https://images.pokemontcg.io/sm10/symbol.png"
  },
  {
    "code": "det1",
    "name": "Detective Pikachu",
    "slug": "detective-pikachu",
    "series": "Sun & Moon",
    "releaseDate": "2019/04/05",
    "total": 18,
    "logo": "https://images.pokemontcg.io/det1/logo.png",
    "symbol": "https://images.pokemontcg.io/det1/symbol.png"
  },
  {
    "code": "sm9",
    "name": "Team Up",
    "slug": "team-up",
    "series": "Sun & Moon",
    "releaseDate": "2019/02/01",
    "total": 181,
    "logo": "https://images.pokemontcg.io/sm9/logo.png",
    "symbol": "https://images.pokemontcg.io/sm9/symbol.png"
  },
  {
    "code": "sm8",
    "name": "Lost Thunder",
    "slug": "lost-thunder",
    "series": "Sun & Moon",
    "releaseDate": "2018/11/02",
    "total": 214,
    "logo": "https://images.pokemontcg.io/sm8/logo.png",
    "symbol": "https://images.pokemontcg.io/sm8/symbol.png"
  },
  {
    "code": "mcd18",
    "name": "McDonald's Collection 2018",
    "slug": "mcdonald-s-collection-2018",
    "series": "Other",
    "releaseDate": "2018/10/16",
    "total": 12,
    "logo": "https://images.pokemontcg.io/mcd18/logo.png",
    "symbol": "https://images.pokemontcg.io/mcd18/symbol.png"
  },
  {
    "code": "sm75",
    "name": "Dragon Majesty",
    "slug": "dragon-majesty",
    "series": "Sun & Moon",
    "releaseDate": "2018/09/07",
    "total": 70,
    "logo": "https://images.pokemontcg.io/sm75/logo.png",
    "symbol": "https://images.pokemontcg.io/sm75/symbol.png"
  },
  {
    "code": "sm7",
    "name": "Celestial Storm",
    "slug": "celestial-storm",
    "series": "Sun & Moon",
    "releaseDate": "2018/08/03",
    "total": 168,
    "logo": "https://images.pokemontcg.io/sm7/logo.png",
    "symbol": "https://images.pokemontcg.io/sm7/symbol.png"
  },
  {
    "code": "sm6",
    "name": "Forbidden Light",
    "slug": "forbidden-light",
    "series": "Sun & Moon",
    "releaseDate": "2018/05/04",
    "total": 131,
    "logo": "https://images.pokemontcg.io/sm6/logo.png",
    "symbol": "https://images.pokemontcg.io/sm6/symbol.png"
  },
  {
    "code": "sm5",
    "name": "Ultra Prism",
    "slug": "ultra-prism",
    "series": "Sun & Moon",
    "releaseDate": "2018/02/02",
    "total": 156,
    "logo": "https://images.pokemontcg.io/sm5/logo.png",
    "symbol": "https://images.pokemontcg.io/sm5/symbol.png"
  },
  {
    "code": "mcd17",
    "name": "McDonald's Collection 2017",
    "slug": "mcdonald-s-collection-2017",
    "series": "Other",
    "releaseDate": "2017/11/07",
    "total": 12,
    "logo": "https://images.pokemontcg.io/mcd17/logo.png",
    "symbol": "https://images.pokemontcg.io/mcd17/symbol.png"
  },
  {
    "code": "sm4",
    "name": "Crimson Invasion",
    "slug": "crimson-invasion",
    "series": "Sun & Moon",
    "releaseDate": "2017/11/03",
    "total": 111,
    "logo": "https://images.pokemontcg.io/sm4/logo.png",
    "symbol": "https://images.pokemontcg.io/sm4/symbol.png"
  },
  {
    "code": "sm35",
    "name": "Shining Legends",
    "slug": "shining-legends",
    "series": "Sun & Moon",
    "releaseDate": "2017/10/06",
    "total": 73,
    "logo": "https://images.pokemontcg.io/sm35/logo.png",
    "symbol": "https://images.pokemontcg.io/sm35/symbol.png"
  },
  {
    "code": "sm3",
    "name": "Burning Shadows",
    "slug": "burning-shadows",
    "series": "Sun & Moon",
    "releaseDate": "2017/08/05",
    "total": 147,
    "logo": "https://images.pokemontcg.io/sm3/logo.png",
    "symbol": "https://images.pokemontcg.io/sm3/symbol.png"
  },
  {
    "code": "sm2",
    "name": "Guardians Rising",
    "slug": "guardians-rising",
    "series": "Sun & Moon",
    "releaseDate": "2017/05/05",
    "total": 145,
    "logo": "https://images.pokemontcg.io/sm2/logo.png",
    "symbol": "https://images.pokemontcg.io/sm2/symbol.png"
  },
  {
    "code": "sm1",
    "name": "Sun & Moon",
    "slug": "sun-moon",
    "series": "Sun & Moon",
    "releaseDate": "2017/02/03",
    "total": 149,
    "logo": "https://images.pokemontcg.io/sm1/logo.png",
    "symbol": "https://images.pokemontcg.io/sm1/symbol.png"
  },
  {
    "code": "smp",
    "name": "SM Black Star Promos",
    "slug": "sm-black-star-promos",
    "series": "Sun & Moon",
    "releaseDate": "2017/02/03",
    "total": 248,
    "logo": "https://images.pokemontcg.io/smp/logo.png",
    "symbol": "https://images.pokemontcg.io/smp/symbol.png"
  },
  {
    "code": "xy12",
    "name": "Evolutions",
    "slug": "evolutions",
    "series": "XY",
    "releaseDate": "2016/11/02",
    "total": 108,
    "logo": "https://images.pokemontcg.io/xy12/logo.png",
    "symbol": "https://images.pokemontcg.io/xy12/symbol.png"
  },
  {
    "code": "mcd16",
    "name": "McDonald's Collection 2016",
    "slug": "mcdonald-s-collection-2016",
    "series": "Other",
    "releaseDate": "2016/08/19",
    "total": 12,
    "logo": "https://images.pokemontcg.io/mcd16/logo.png",
    "symbol": "https://images.pokemontcg.io/mcd16/symbol.png"
  },
  {
    "code": "xy11",
    "name": "Steam Siege",
    "slug": "steam-siege",
    "series": "XY",
    "releaseDate": "2016/08/03",
    "total": 114,
    "logo": "https://images.pokemontcg.io/xy11/logo.png",
    "symbol": "https://images.pokemontcg.io/xy11/symbol.png"
  },
  {
    "code": "xy10",
    "name": "Fates Collide",
    "slug": "fates-collide",
    "series": "XY",
    "releaseDate": "2016/05/02",
    "total": 124,
    "logo": "https://images.pokemontcg.io/xy10/logo.png",
    "symbol": "https://images.pokemontcg.io/xy10/symbol.png"
  },
  {
    "code": "g1",
    "name": "Generations",
    "slug": "generations",
    "series": "XY",
    "releaseDate": "2016/02/22",
    "total": 83,
    "logo": "https://images.pokemontcg.io/g1/logo.png",
    "symbol": "https://images.pokemontcg.io/g1/symbol.png"
  },
  {
    "code": "xy9",
    "name": "BREAKpoint",
    "slug": "breakpoint",
    "series": "XY",
    "releaseDate": "2016/02/03",
    "total": 122,
    "logo": "https://images.pokemontcg.io/xy9/logo.png",
    "symbol": "https://images.pokemontcg.io/xy9/symbol.png"
  },
  {
    "code": "mcd15",
    "name": "McDonald's Collection 2015",
    "slug": "mcdonald-s-collection-2015",
    "series": "Other",
    "releaseDate": "2015/11/27",
    "total": 12,
    "logo": "https://images.pokemontcg.io/mcd15/logo.png",
    "symbol": "https://images.pokemontcg.io/mcd15/symbol.png"
  },
  {
    "code": "xy8",
    "name": "BREAKthrough",
    "slug": "breakthrough",
    "series": "XY",
    "releaseDate": "2015/11/04",
    "total": 162,
    "logo": "https://images.pokemontcg.io/xy8/logo.png",
    "symbol": "https://images.pokemontcg.io/xy8/symbol.png"
  },
  {
    "code": "xy7",
    "name": "Ancient Origins",
    "slug": "ancient-origins",
    "series": "XY",
    "releaseDate": "2015/08/12",
    "total": 98,
    "logo": "https://images.pokemontcg.io/xy7/logo.png",
    "symbol": "https://images.pokemontcg.io/xy7/symbol.png"
  },
  {
    "code": "xy6",
    "name": "Roaring Skies",
    "slug": "roaring-skies",
    "series": "XY",
    "releaseDate": "2015/05/06",
    "total": 108,
    "logo": "https://images.pokemontcg.io/xy6/logo.png",
    "symbol": "https://images.pokemontcg.io/xy6/symbol.png"
  },
  {
    "code": "dc1",
    "name": "Double Crisis",
    "slug": "double-crisis",
    "series": "XY",
    "releaseDate": "2015/03/25",
    "total": 34,
    "logo": "https://images.pokemontcg.io/dc1/logo.png",
    "symbol": "https://images.pokemontcg.io/dc1/symbol.png"
  },
  {
    "code": "xy5",
    "name": "Primal Clash",
    "slug": "primal-clash",
    "series": "XY",
    "releaseDate": "2015/02/04",
    "total": 160,
    "logo": "https://images.pokemontcg.io/xy5/logo.png",
    "symbol": "https://images.pokemontcg.io/xy5/symbol.png"
  },
  {
    "code": "xy4",
    "name": "Phantom Forces",
    "slug": "phantom-forces",
    "series": "XY",
    "releaseDate": "2014/11/05",
    "total": 119,
    "logo": "https://images.pokemontcg.io/xy4/logo.png",
    "symbol": "https://images.pokemontcg.io/xy4/symbol.png"
  },
  {
    "code": "xy3",
    "name": "Furious Fists",
    "slug": "furious-fists",
    "series": "XY",
    "releaseDate": "2014/08/13",
    "total": 111,
    "logo": "https://images.pokemontcg.io/xy3/logo.png",
    "symbol": "https://images.pokemontcg.io/xy3/symbol.png"
  },
  {
    "code": "mcd14",
    "name": "McDonald's Collection 2014",
    "slug": "mcdonald-s-collection-2014",
    "series": "Other",
    "releaseDate": "2014/05/23",
    "total": 12,
    "logo": "https://images.pokemontcg.io/mcd14/logo.png",
    "symbol": "https://images.pokemontcg.io/mcd14/symbol.png"
  },
  {
    "code": "xy2",
    "name": "Flashfire",
    "slug": "flashfire",
    "series": "XY",
    "releaseDate": "2014/05/07",
    "total": 106,
    "logo": "https://images.pokemontcg.io/xy2/logo.png",
    "symbol": "https://images.pokemontcg.io/xy2/symbol.png"
  },
  {
    "code": "xy1",
    "name": "XY",
    "slug": "xy",
    "series": "XY",
    "releaseDate": "2014/02/05",
    "total": 146,
    "logo": "https://images.pokemontcg.io/xy1/logo.png",
    "symbol": "https://images.pokemontcg.io/xy1/symbol.png"
  },
  {
    "code": "xy0",
    "name": "Kalos Starter Set",
    "slug": "kalos-starter-set",
    "series": "XY",
    "releaseDate": "2013/11/08",
    "total": 39,
    "logo": "https://images.pokemontcg.io/xy0/logo.png",
    "symbol": "https://images.pokemontcg.io/xy0/symbol.png"
  },
  {
    "code": "bw11",
    "name": "Legendary Treasures",
    "slug": "legendary-treasures",
    "series": "Black & White",
    "releaseDate": "2013/11/06",
    "total": 113,
    "logo": "https://images.pokemontcg.io/bw11/logo.png",
    "symbol": "https://images.pokemontcg.io/bw11/symbol.png"
  },
  {
    "code": "xyp",
    "name": "XY Black Star Promos",
    "slug": "xy-black-star-promos",
    "series": "XY",
    "releaseDate": "2013/10/12",
    "total": 211,
    "logo": "https://images.pokemontcg.io/xyp/logo.png",
    "symbol": "https://images.pokemontcg.io/xyp/symbol.png"
  },
  {
    "code": "bw10",
    "name": "Plasma Blast",
    "slug": "plasma-blast",
    "series": "Black & White",
    "releaseDate": "2013/08/14",
    "total": 101,
    "logo": "https://images.pokemontcg.io/bw10/logo.png",
    "symbol": "https://images.pokemontcg.io/bw10/symbol.png"
  },
  {
    "code": "bw9",
    "name": "Plasma Freeze",
    "slug": "plasma-freeze",
    "series": "Black & White",
    "releaseDate": "2013/05/08",
    "total": 116,
    "logo": "https://images.pokemontcg.io/bw9/logo.png",
    "symbol": "https://images.pokemontcg.io/bw9/symbol.png"
  },
  {
    "code": "bw8",
    "name": "Plasma Storm",
    "slug": "plasma-storm",
    "series": "Black & White",
    "releaseDate": "2013/02/06",
    "total": 135,
    "logo": "https://images.pokemontcg.io/bw8/logo.png",
    "symbol": "https://images.pokemontcg.io/bw8/symbol.png"
  },
  {
    "code": "bw7",
    "name": "Boundaries Crossed",
    "slug": "boundaries-crossed",
    "series": "Black & White",
    "releaseDate": "2012/11/07",
    "total": 149,
    "logo": "https://images.pokemontcg.io/bw7/logo.png",
    "symbol": "https://images.pokemontcg.io/bw7/symbol.png"
  },
  {
    "code": "dv1",
    "name": "Dragon Vault",
    "slug": "dragon-vault",
    "series": "Black & White",
    "releaseDate": "2012/10/05",
    "total": 20,
    "logo": "https://images.pokemontcg.io/dv1/logo.png",
    "symbol": "https://images.pokemontcg.io/dv1/symbol.png"
  },
  {
    "code": "bw6",
    "name": "Dragons Exalted",
    "slug": "dragons-exalted",
    "series": "Black & White",
    "releaseDate": "2012/08/15",
    "total": 124,
    "logo": "https://images.pokemontcg.io/bw6/logo.png",
    "symbol": "https://images.pokemontcg.io/bw6/symbol.png"
  },
  {
    "code": "mcd12",
    "name": "McDonald's Collection 2012",
    "slug": "mcdonald-s-collection-2012",
    "series": "Other",
    "releaseDate": "2012/06/15",
    "total": 12,
    "logo": "https://images.pokemontcg.io/mcd12/logo.png",
    "symbol": "https://images.pokemontcg.io/mcd12/symbol.png"
  },
  {
    "code": "bw5",
    "name": "Dark Explorers",
    "slug": "dark-explorers",
    "series": "Black & White",
    "releaseDate": "2012/05/09",
    "total": 108,
    "logo": "https://images.pokemontcg.io/bw5/logo.png",
    "symbol": "https://images.pokemontcg.io/bw5/symbol.png"
  },
  {
    "code": "bw4",
    "name": "Next Destinies",
    "slug": "next-destinies",
    "series": "Black & White",
    "releaseDate": "2012/02/08",
    "total": 99,
    "logo": "https://images.pokemontcg.io/bw4/logo.png",
    "symbol": "https://images.pokemontcg.io/bw4/symbol.png"
  },
  {
    "code": "bw3",
    "name": "Noble Victories",
    "slug": "noble-victories",
    "series": "Black & White",
    "releaseDate": "2011/11/16",
    "total": 101,
    "logo": "https://images.pokemontcg.io/bw3/logo.png",
    "symbol": "https://images.pokemontcg.io/bw3/symbol.png"
  },
  {
    "code": "bw2",
    "name": "Emerging Powers",
    "slug": "emerging-powers",
    "series": "Black & White",
    "releaseDate": "2011/08/31",
    "total": 98,
    "logo": "https://images.pokemontcg.io/bw2/logo.png",
    "symbol": "https://images.pokemontcg.io/bw2/symbol.png"
  },
  {
    "code": "mcd11",
    "name": "McDonald's Collection 2011",
    "slug": "mcdonald-s-collection-2011",
    "series": "Other",
    "releaseDate": "2011/06/17",
    "total": 12,
    "logo": "https://images.pokemontcg.io/mcd11/logo.png",
    "symbol": "https://images.pokemontcg.io/mcd11/symbol.png"
  },
  {
    "code": "bw1",
    "name": "Black & White",
    "slug": "black-white",
    "series": "Black & White",
    "releaseDate": "2011/04/25",
    "total": 114,
    "logo": "https://images.pokemontcg.io/bw1/logo.png",
    "symbol": "https://images.pokemontcg.io/bw1/symbol.png"
  },
  {
    "code": "bwp",
    "name": "BW Black Star Promos",
    "slug": "bw-black-star-promos",
    "series": "Black & White",
    "releaseDate": "2011/03/01",
    "total": 101,
    "logo": "https://images.pokemontcg.io/bwp/logo.png",
    "symbol": "https://images.pokemontcg.io/bwp/symbol.png"
  },
  {
    "code": "col1",
    "name": "Call of Legends",
    "slug": "call-of-legends",
    "series": "HeartGold & SoulSilver",
    "releaseDate": "2011/02/09",
    "total": 95,
    "logo": "https://images.pokemontcg.io/col1/logo.png",
    "symbol": "https://images.pokemontcg.io/col1/symbol.png"
  },
  {
    "code": "hgss4",
    "name": "HS—Triumphant",
    "slug": "hs-triumphant",
    "series": "HeartGold & SoulSilver",
    "releaseDate": "2010/11/03",
    "total": 102,
    "logo": "https://images.pokemontcg.io/hgss4/logo.png",
    "symbol": "https://images.pokemontcg.io/hgss4/symbol.png"
  },
  {
    "code": "hgss3",
    "name": "HS—Undaunted",
    "slug": "hs-undaunted",
    "series": "HeartGold & SoulSilver",
    "releaseDate": "2010/08/18",
    "total": 90,
    "logo": "https://images.pokemontcg.io/hgss3/logo.png",
    "symbol": "https://images.pokemontcg.io/hgss3/symbol.png"
  },
  {
    "code": "hgss2",
    "name": "HS—Unleashed",
    "slug": "hs-unleashed",
    "series": "HeartGold & SoulSilver",
    "releaseDate": "2010/05/12",
    "total": 95,
    "logo": "https://images.pokemontcg.io/hgss2/logo.png",
    "symbol": "https://images.pokemontcg.io/hgss2/symbol.png"
  },
  {
    "code": "hgss1",
    "name": "HeartGold & SoulSilver",
    "slug": "heartgold-soulsilver",
    "series": "HeartGold & SoulSilver",
    "releaseDate": "2010/02/10",
    "total": 123,
    "logo": "https://images.pokemontcg.io/hgss1/logo.png",
    "symbol": "https://images.pokemontcg.io/hgss1/symbol.png"
  },
  {
    "code": "hsp",
    "name": "HGSS Black Star Promos",
    "slug": "hgss-black-star-promos",
    "series": "HeartGold & SoulSilver",
    "releaseDate": "2010/02/10",
    "total": 25,
    "logo": "https://images.pokemontcg.io/hsp/logo.png",
    "symbol": "https://images.pokemontcg.io/hsp/symbol.png"
  },
  {
    "code": "ru1",
    "name": "Pokémon Rumble",
    "slug": "pok-mon-rumble",
    "series": "Other",
    "releaseDate": "2009/12/02",
    "total": 16,
    "logo": "https://images.pokemontcg.io/ru1/logo.png",
    "symbol": "https://images.pokemontcg.io/ru1/symbol.png"
  },
  {
    "code": "pl4",
    "name": "Arceus",
    "slug": "arceus",
    "series": "Platinum",
    "releaseDate": "2009/11/04",
    "total": 99,
    "logo": "https://images.pokemontcg.io/pl4/logo.png",
    "symbol": "https://images.pokemontcg.io/pl4/symbol.png"
  },
  {
    "code": "pl3",
    "name": "Supreme Victors",
    "slug": "supreme-victors",
    "series": "Platinum",
    "releaseDate": "2009/08/19",
    "total": 147,
    "logo": "https://images.pokemontcg.io/pl3/logo.png",
    "symbol": "https://images.pokemontcg.io/pl3/symbol.png"
  },
  {
    "code": "pl2",
    "name": "Rising Rivals",
    "slug": "rising-rivals",
    "series": "Platinum",
    "releaseDate": "2009/05/16",
    "total": 111,
    "logo": "https://images.pokemontcg.io/pl2/logo.png",
    "symbol": "https://images.pokemontcg.io/pl2/symbol.png"
  },
  {
    "code": "pop9",
    "name": "POP Series 9",
    "slug": "pop-series-9",
    "series": "POP",
    "releaseDate": "2009/03/01",
    "total": 17,
    "logo": "https://images.pokemontcg.io/pop9/logo.png",
    "symbol": "https://images.pokemontcg.io/pop9/symbol.png"
  },
  {
    "code": "pl1",
    "name": "Platinum",
    "slug": "platinum",
    "series": "Platinum",
    "releaseDate": "2009/02/11",
    "total": 127,
    "logo": "https://images.pokemontcg.io/pl1/logo.png",
    "symbol": "https://images.pokemontcg.io/pl1/symbol.png"
  },
  {
    "code": "dp7",
    "name": "Stormfront",
    "slug": "stormfront",
    "series": "Diamond & Pearl",
    "releaseDate": "2008/11/01",
    "total": 100,
    "logo": "https://images.pokemontcg.io/dp7/logo.png",
    "symbol": "https://images.pokemontcg.io/dp7/symbol.png"
  },
  {
    "code": "pop8",
    "name": "POP Series 8",
    "slug": "pop-series-8",
    "series": "POP",
    "releaseDate": "2008/09/01",
    "total": 17,
    "logo": "https://images.pokemontcg.io/pop8/logo.png",
    "symbol": "https://images.pokemontcg.io/pop8/symbol.png"
  },
  {
    "code": "dp6",
    "name": "Legends Awakened",
    "slug": "legends-awakened",
    "series": "Diamond & Pearl",
    "releaseDate": "2008/08/01",
    "total": 146,
    "logo": "https://images.pokemontcg.io/dp6/logo.png",
    "symbol": "https://images.pokemontcg.io/dp6/symbol.png"
  },
  {
    "code": "dp5",
    "name": "Majestic Dawn",
    "slug": "majestic-dawn",
    "series": "Diamond & Pearl",
    "releaseDate": "2008/05/01",
    "total": 100,
    "logo": "https://images.pokemontcg.io/dp5/logo.png",
    "symbol": "https://images.pokemontcg.io/dp5/symbol.png"
  },
  {
    "code": "pop7",
    "name": "POP Series 7",
    "slug": "pop-series-7",
    "series": "POP",
    "releaseDate": "2008/03/01",
    "total": 17,
    "logo": "https://images.pokemontcg.io/pop7/logo.png",
    "symbol": "https://images.pokemontcg.io/pop7/symbol.png"
  },
  {
    "code": "dp4",
    "name": "Great Encounters",
    "slug": "great-encounters",
    "series": "Diamond & Pearl",
    "releaseDate": "2008/02/01",
    "total": 106,
    "logo": "https://images.pokemontcg.io/dp4/logo.png",
    "symbol": "https://images.pokemontcg.io/dp4/symbol.png"
  },
  {
    "code": "dp3",
    "name": "Secret Wonders",
    "slug": "secret-wonders",
    "series": "Diamond & Pearl",
    "releaseDate": "2007/11/01",
    "total": 132,
    "logo": "https://images.pokemontcg.io/dp3/logo.png",
    "symbol": "https://images.pokemontcg.io/dp3/symbol.png"
  },
  {
    "code": "pop6",
    "name": "POP Series 6",
    "slug": "pop-series-6",
    "series": "POP",
    "releaseDate": "2007/09/01",
    "total": 17,
    "logo": "https://images.pokemontcg.io/pop6/logo.png",
    "symbol": "https://images.pokemontcg.io/pop6/symbol.png"
  },
  {
    "code": "dp2",
    "name": "Mysterious Treasures",
    "slug": "mysterious-treasures",
    "series": "Diamond & Pearl",
    "releaseDate": "2007/08/01",
    "total": 123,
    "logo": "https://images.pokemontcg.io/dp2/logo.png",
    "symbol": "https://images.pokemontcg.io/dp2/symbol.png"
  },
  {
    "code": "dp1",
    "name": "Diamond & Pearl",
    "slug": "diamond-pearl",
    "series": "Diamond & Pearl",
    "releaseDate": "2007/05/01",
    "total": 130,
    "logo": "https://images.pokemontcg.io/dp1/logo.png",
    "symbol": "https://images.pokemontcg.io/dp1/symbol.png"
  },
  {
    "code": "dpp",
    "name": "DP Black Star Promos",
    "slug": "dp-black-star-promos",
    "series": "Diamond & Pearl",
    "releaseDate": "2007/05/01",
    "total": 56,
    "logo": "https://images.pokemontcg.io/dpp/logo.png",
    "symbol": "https://images.pokemontcg.io/dpp/symbol.png"
  },
  {
    "code": "pop5",
    "name": "POP Series 5",
    "slug": "pop-series-5",
    "series": "POP",
    "releaseDate": "2007/03/01",
    "total": 17,
    "logo": "https://images.pokemontcg.io/pop5/logo.png",
    "symbol": "https://images.pokemontcg.io/pop5/symbol.png"
  },
  {
    "code": "ex16",
    "name": "Power Keepers",
    "slug": "power-keepers",
    "series": "EX",
    "releaseDate": "2007/02/02",
    "total": 108,
    "logo": "https://images.pokemontcg.io/ex16/logo.png",
    "symbol": "https://images.pokemontcg.io/ex16/symbol.png"
  },
  {
    "code": "ex15",
    "name": "Dragon Frontiers",
    "slug": "dragon-frontiers",
    "series": "EX",
    "releaseDate": "2006/11/01",
    "total": 101,
    "logo": "https://images.pokemontcg.io/ex15/logo.png",
    "symbol": "https://images.pokemontcg.io/ex15/symbol.png"
  },
  {
    "code": "ex14",
    "name": "Crystal Guardians",
    "slug": "crystal-guardians",
    "series": "EX",
    "releaseDate": "2006/08/01",
    "total": 100,
    "logo": "https://images.pokemontcg.io/ex14/logo.png",
    "symbol": "https://images.pokemontcg.io/ex14/symbol.png"
  },
  {
    "code": "pop4",
    "name": "POP Series 4",
    "slug": "pop-series-4",
    "series": "POP",
    "releaseDate": "2006/08/01",
    "total": 17,
    "logo": "https://images.pokemontcg.io/pop4/logo.png",
    "symbol": "https://images.pokemontcg.io/pop4/symbol.png"
  },
  {
    "code": "ex13",
    "name": "Holon Phantoms",
    "slug": "holon-phantoms",
    "series": "EX",
    "releaseDate": "2006/05/01",
    "total": 110,
    "logo": "https://images.pokemontcg.io/ex13/logo.png",
    "symbol": "https://images.pokemontcg.io/ex13/symbol.png"
  },
  {
    "code": "pop3",
    "name": "POP Series 3",
    "slug": "pop-series-3",
    "series": "POP",
    "releaseDate": "2006/04/01",
    "total": 17,
    "logo": "https://images.pokemontcg.io/pop3/logo.png",
    "symbol": "https://images.pokemontcg.io/pop3/symbol.png"
  },
  {
    "code": "tk2a",
    "name": "EX Trainer Kit 2 Plusle",
    "slug": "ex-trainer-kit-2-plusle",
    "series": "EX",
    "releaseDate": "2006/03/01",
    "total": 12,
    "logo": "https://images.pokemontcg.io/tk2a/logo.png",
    "symbol": "https://images.pokemontcg.io/tk2a/symbol.png"
  },
  {
    "code": "tk2b",
    "name": "EX Trainer Kit 2 Minun",
    "slug": "ex-trainer-kit-2-minun",
    "series": "EX",
    "releaseDate": "2006/03/01",
    "total": 12,
    "logo": "https://images.pokemontcg.io/tk2b/logo.png",
    "symbol": "https://images.pokemontcg.io/tk2b/symbol.png"
  },
  {
    "code": "ex12",
    "name": "Legend Maker",
    "slug": "legend-maker",
    "series": "EX",
    "releaseDate": "2006/02/01",
    "total": 92,
    "logo": "https://images.pokemontcg.io/ex12/logo.png",
    "symbol": "https://images.pokemontcg.io/ex12/symbol.png"
  },
  {
    "code": "ex11",
    "name": "Delta Species",
    "slug": "delta-species",
    "series": "EX",
    "releaseDate": "2005/10/31",
    "total": 113,
    "logo": "https://images.pokemontcg.io/ex11/logo.png",
    "symbol": "https://images.pokemontcg.io/ex11/symbol.png"
  },
  {
    "code": "ex10",
    "name": "Unseen Forces",
    "slug": "unseen-forces",
    "series": "EX",
    "releaseDate": "2005/08/01",
    "total": 115,
    "logo": "https://images.pokemontcg.io/ex10/logo.png",
    "symbol": "https://images.pokemontcg.io/ex10/symbol.png"
  },
  {
    "code": "pop2",
    "name": "POP Series 2",
    "slug": "pop-series-2",
    "series": "POP",
    "releaseDate": "2005/08/01",
    "total": 17,
    "logo": "https://images.pokemontcg.io/pop2/logo.png",
    "symbol": "https://images.pokemontcg.io/pop2/symbol.png"
  },
  {
    "code": "ex9",
    "name": "Emerald",
    "slug": "emerald",
    "series": "EX",
    "releaseDate": "2005/05/01",
    "total": 106,
    "logo": "https://images.pokemontcg.io/ex9/logo.png",
    "symbol": "https://images.pokemontcg.io/ex9/symbol.png"
  },
  {
    "code": "ex8",
    "name": "Deoxys",
    "slug": "deoxys",
    "series": "EX",
    "releaseDate": "2005/02/01",
    "total": 107,
    "logo": "https://images.pokemontcg.io/ex8/logo.png",
    "symbol": "https://images.pokemontcg.io/ex8/symbol.png"
  },
  {
    "code": "ex7",
    "name": "Team Rocket Returns",
    "slug": "team-rocket-returns",
    "series": "EX",
    "releaseDate": "2004/11/01",
    "total": 109,
    "logo": "https://images.pokemontcg.io/ex7/logo.png",
    "symbol": "https://images.pokemontcg.io/ex7/symbol.png"
  },
  {
    "code": "ex6",
    "name": "FireRed & LeafGreen",
    "slug": "firered-leafgreen",
    "series": "EX",
    "releaseDate": "2004/09/01",
    "total": 112,
    "logo": "https://images.pokemontcg.io/ex6/logo.png",
    "symbol": "https://images.pokemontcg.io/ex6/symbol.png"
  },
  {
    "code": "pop1",
    "name": "POP Series 1",
    "slug": "pop-series-1",
    "series": "POP",
    "releaseDate": "2004/09/01",
    "total": 17,
    "logo": "https://images.pokemontcg.io/pop1/logo.png",
    "symbol": "https://images.pokemontcg.io/pop1/symbol.png"
  },
  {
    "code": "tk1a",
    "name": "EX Trainer Kit Latias",
    "slug": "ex-trainer-kit-latias",
    "series": "EX",
    "releaseDate": "2004/06/01",
    "total": 10,
    "logo": "https://images.pokemontcg.io/tk1a/logo.png",
    "symbol": "https://images.pokemontcg.io/tk1a/symbol.png"
  },
  {
    "code": "tk1b",
    "name": "EX Trainer Kit Latios",
    "slug": "ex-trainer-kit-latios",
    "series": "EX",
    "releaseDate": "2004/06/01",
    "total": 10,
    "logo": "https://images.pokemontcg.io/tk1b/logo.png",
    "symbol": "https://images.pokemontcg.io/tk1b/symbol.png"
  },
  {
    "code": "ex5",
    "name": "Hidden Legends",
    "slug": "hidden-legends",
    "series": "EX",
    "releaseDate": "2004/06/01",
    "total": 101,
    "logo": "https://images.pokemontcg.io/ex5/logo.png",
    "symbol": "https://images.pokemontcg.io/ex5/symbol.png"
  },
  {
    "code": "ex4",
    "name": "Team Magma vs Team Aqua",
    "slug": "team-magma-vs-team-aqua",
    "series": "EX",
    "releaseDate": "2004/03/01",
    "total": 95,
    "logo": "https://images.pokemontcg.io/ex4/logo.png",
    "symbol": "https://images.pokemontcg.io/ex4/symbol.png"
  },
  {
    "code": "ex3",
    "name": "Dragon",
    "slug": "dragon",
    "series": "EX",
    "releaseDate": "2003/11/24",
    "total": 97,
    "logo": "https://images.pokemontcg.io/ex3/logo.png",
    "symbol": "https://images.pokemontcg.io/ex3/symbol.png"
  },
  {
    "code": "np",
    "name": "Nintendo Black Star Promos",
    "slug": "nintendo-black-star-promos",
    "series": "NP",
    "releaseDate": "2003/10/01",
    "total": 40,
    "logo": "https://images.pokemontcg.io/np/logo.png",
    "symbol": "https://images.pokemontcg.io/np/symbol.png"
  },
  {
    "code": "ex2",
    "name": "Sandstorm",
    "slug": "sandstorm",
    "series": "EX",
    "releaseDate": "2003/09/18",
    "total": 100,
    "logo": "https://images.pokemontcg.io/ex2/logo.png",
    "symbol": "https://images.pokemontcg.io/ex2/symbol.png"
  },
  {
    "code": "ex1",
    "name": "Ruby & Sapphire",
    "slug": "ruby-sapphire",
    "series": "EX",
    "releaseDate": "2003/07/01",
    "total": 109,
    "logo": "https://images.pokemontcg.io/ex1/logo.png",
    "symbol": "https://images.pokemontcg.io/ex1/symbol.png"
  },
  {
    "code": "ecard3",
    "name": "Skyridge",
    "slug": "skyridge",
    "series": "E-Card",
    "releaseDate": "2003/05/12",
    "total": 144,
    "logo": "https://images.pokemontcg.io/ecard3/logo.png",
    "symbol": "https://images.pokemontcg.io/ecard3/symbol.png"
  },
  {
    "code": "ecard2",
    "name": "Aquapolis",
    "slug": "aquapolis",
    "series": "E-Card",
    "releaseDate": "2003/01/15",
    "total": 147,
    "logo": "https://images.pokemontcg.io/ecard2/logo.png",
    "symbol": "https://images.pokemontcg.io/ecard2/symbol.png"
  },
  {
    "code": "bp",
    "name": "Best of Game",
    "slug": "best-of-game",
    "series": "Other",
    "releaseDate": "2002/12/01",
    "total": 9,
    "logo": "https://images.pokemontcg.io/bp/logo.png",
    "symbol": "https://images.pokemontcg.io/bp/symbol.png"
  },
  {
    "code": "ecard1",
    "name": "Expedition Base Set",
    "slug": "expedition-base-set",
    "series": "E-Card",
    "releaseDate": "2002/09/15",
    "total": 165,
    "logo": "https://images.pokemontcg.io/ecard1/logo.png",
    "symbol": "https://images.pokemontcg.io/ecard1/symbol.png"
  },
  {
    "code": "base6",
    "name": "Legendary Collection",
    "slug": "legendary-collection",
    "series": "Other",
    "releaseDate": "2002/05/24",
    "total": 110,
    "logo": "https://images.pokemontcg.io/base6/logo.png",
    "symbol": "https://images.pokemontcg.io/base6/symbol.png"
  },
  {
    "code": "neo4",
    "name": "Neo Destiny",
    "slug": "neo-destiny",
    "series": "Neo",
    "releaseDate": "2002/02/28",
    "total": 105,
    "logo": "https://images.pokemontcg.io/neo4/logo.png",
    "symbol": "https://images.pokemontcg.io/neo4/symbol.png"
  },
  {
    "code": "neo3",
    "name": "Neo Revelation",
    "slug": "neo-revelation",
    "series": "Neo",
    "releaseDate": "2001/09/21",
    "total": 64,
    "logo": "https://images.pokemontcg.io/neo3/logo.png",
    "symbol": "https://images.pokemontcg.io/neo3/symbol.png"
  },
  {
    "code": "si1",
    "name": "Southern Islands",
    "slug": "southern-islands",
    "series": "Other",
    "releaseDate": "2001/07/31",
    "total": 18,
    "logo": "https://images.pokemontcg.io/si1/logo.png",
    "symbol": "https://images.pokemontcg.io/si1/symbol.png"
  },
  {
    "code": "neo2",
    "name": "Neo Discovery",
    "slug": "neo-discovery",
    "series": "Neo",
    "releaseDate": "2001/06/01",
    "total": 75,
    "logo": "https://images.pokemontcg.io/neo2/logo.png",
    "symbol": "https://images.pokemontcg.io/neo2/symbol.png"
  },
  {
    "code": "neo1",
    "name": "Neo Genesis",
    "slug": "neo-genesis",
    "series": "Neo",
    "releaseDate": "2000/12/16",
    "total": 111,
    "logo": "https://images.pokemontcg.io/neo1/logo.png",
    "symbol": "https://images.pokemontcg.io/neo1/symbol.png"
  },
  {
    "code": "gym2",
    "name": "Gym Challenge",
    "slug": "gym-challenge",
    "series": "Gym",
    "releaseDate": "2000/10/16",
    "total": 132,
    "logo": "https://images.pokemontcg.io/gym2/logo.png",
    "symbol": "https://images.pokemontcg.io/gym2/symbol.png"
  },
  {
    "code": "gym1",
    "name": "Gym Heroes",
    "slug": "gym-heroes",
    "series": "Gym",
    "releaseDate": "2000/08/14",
    "total": 132,
    "logo": "https://images.pokemontcg.io/gym1/logo.png",
    "symbol": "https://images.pokemontcg.io/gym1/symbol.png"
  },
  {
    "code": "base5",
    "name": "Team Rocket",
    "slug": "team-rocket",
    "series": "Base",
    "releaseDate": "2000/04/24",
    "total": 82,
    "logo": "https://images.pokemontcg.io/base5/logo.png",
    "symbol": "https://images.pokemontcg.io/base5/symbol.png"
  },
  {
    "code": "base4",
    "name": "Base Set 2",
    "slug": "base-set-2",
    "series": "Base",
    "releaseDate": "2000/02/24",
    "total": 130,
    "logo": "https://images.pokemontcg.io/base4/logo.png",
    "symbol": "https://images.pokemontcg.io/base4/symbol.png"
  },
  {
    "code": "base3",
    "name": "Fossil",
    "slug": "fossil",
    "series": "Base",
    "releaseDate": "1999/10/10",
    "total": 62,
    "logo": "https://images.pokemontcg.io/base3/logo.png",
    "symbol": "https://images.pokemontcg.io/base3/symbol.png"
  },
  {
    "code": "basep",
    "name": "Wizards Black Star Promos",
    "slug": "wizards-black-star-promos",
    "series": "Base",
    "releaseDate": "1999/07/01",
    "total": 53,
    "logo": "https://images.pokemontcg.io/basep/logo.png",
    "symbol": "https://images.pokemontcg.io/basep/symbol.png"
  },
  {
    "code": "base2",
    "name": "Jungle",
    "slug": "jungle",
    "series": "Base",
    "releaseDate": "1999/06/16",
    "total": 64,
    "logo": "https://images.pokemontcg.io/base2/logo.png",
    "symbol": "https://images.pokemontcg.io/base2/symbol.png"
  },
  {
    "code": "base1",
    "name": "Base",
    "slug": "base",
    "series": "Base",
    "releaseDate": "1999/01/09",
    "total": 102,
    "logo": "https://images.pokemontcg.io/base1/logo.png",
    "symbol": "https://images.pokemontcg.io/base1/symbol.png"
  }
];
