// Builds DexCompare's seed inputs from the offline PokemonTCG/pokemon-tcg-data
// mirror (prisma/pokemon-data). Produces:
//   prisma/pokemon-cards.json  — flat card rows ready for the seeder
//   src/lib/pokemon-sets.ts    — the SETS catalogue (used by constants.ts + UI)
// Run:  npx tsx scripts/build-pokemon-data.ts
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const DATA = join(process.cwd(), "prisma", "pokemon-data");

interface RawSet {
  id: string;
  name: string;
  series: string;
  printedTotal: number;
  total: number;
  releaseDate: string; // YYYY/MM/DD
  ptcgoCode?: string;
  images?: { symbol?: string; logo?: string };
}

interface RawCard {
  id: string;
  name: string;
  supertype: string;
  subtypes?: string[];
  hp?: string;
  types?: string[];
  rarity?: string;
  number: string;
  artist?: string;
  flavorText?: string;
  images?: { small?: string; large?: string };
}

function slugify(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

const sets = JSON.parse(readFileSync(join(DATA, "sets.json"), "utf8")) as RawSet[];
const setById = new Map(sets.map((s) => [s.id, s]));

// ---- SETS catalogue (newest first) -----------------------------------------
const sortedSets = [...sets].sort((a, b) => b.releaseDate.localeCompare(a.releaseDate));
const usedSlugs = new Set<string>();
const setEntries = sortedSets.map((s) => {
  let slug = slugify(s.name);
  while (usedSlugs.has(slug)) slug = `${slug}-${s.id}`;
  usedSlugs.add(slug);
  return {
    code: s.id,
    name: s.name,
    slug,
    series: s.series,
    releaseDate: s.releaseDate,
    total: s.printedTotal || s.total,
    logo: s.images?.logo ?? null,
    symbol: s.images?.symbol ?? null,
  };
});

const setsTs = `// AUTO-GENERATED by scripts/build-pokemon-data.ts — do not edit by hand.
// The full Pokémon TCG set catalogue (${setEntries.length} sets), newest first.
export interface PokemonSet {
  code: string;
  name: string;
  slug: string;
  series: string;
  releaseDate: string;
  total: number;
  logo: string | null;
  symbol: string | null;
}
export const POKEMON_SETS: PokemonSet[] = ${JSON.stringify(setEntries, null, 2)};
`;
writeFileSync(join(process.cwd(), "src", "lib", "pokemon-sets.ts"), setsTs);
console.log(`Wrote src/lib/pokemon-sets.ts (${setEntries.length} sets).`);

// ---- flat card rows ---------------------------------------------------------
const files = readdirSync(join(DATA, "cards")).filter((f) => f.endsWith(".json"));
const rows: Record<string, unknown>[] = [];
for (const file of files) {
  const cards = JSON.parse(readFileSync(join(DATA, "cards", file), "utf8")) as RawCard[];
  for (const c of cards) {
    const set = setById.get(c.id.replace(/-[^-]+$/, "")) ?? setById.get(file.replace(".json", ""));
    const setCode = set?.id ?? file.replace(".json", "");
    const printed = set?.printedTotal || set?.total || 0;
    const isPokemon = c.supertype === "Pokémon";
    const domain = isPokemon && c.types && c.types.length ? c.types[0] : "Colorless";
    rows.push({
      externalId: c.id,
      name: c.name,
      setCode,
      setName: set?.name ?? setCode,
      releaseDate: set?.releaseDate ?? "1999/01/01",
      collectorNumber: printed ? `${c.number}/${printed}` : c.number,
      number: c.number,
      domain,
      type: c.supertype, // Pokémon | Trainer | Energy
      subtype: (c.subtypes ?? []).join(", ") || null,
      rarity: c.rarity ?? "Common",
      hp: c.hp ? parseInt(c.hp, 10) : null,
      artist: c.artist ?? null,
      flavorText: c.flavorText ?? null,
      imageUrl: c.images?.large ?? null,
      imageThumbUrl: c.images?.small ?? null,
    });
  }
}
writeFileSync(join(process.cwd(), "prisma", "pokemon-cards.json"), JSON.stringify(rows));
console.log(`Wrote prisma/pokemon-cards.json (${rows.length} cards).`);
