// Builds the FULL One Piece Card Game catalogue from apitcg.com.
// Needs a free API key (https://apitcg.com) and the host reachable — run locally,
// in CI, or once apitcg.com is on the network-egress allowlist:
//   APITCG_API_KEY=xxxx node prisma/fetch-op.mjs
//
// Emits prisma/op-cards.json (every card, with real image URLs) and rewrites
// src/lib/one-piece-sets.ts. Then: npx prisma db push && npx tsx prisma/seed.ts
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const KEY = process.env.APITCG_API_KEY;
if (!KEY) { console.error("Set APITCG_API_KEY (free at https://apitcg.com)."); process.exit(1); }

const COLORS = ["Red", "Green", "Blue", "Purple", "Black", "Yellow"];
const slugify = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60);

function domainOf(card) {
  const c = (card.color || "").split("/").map((x) => x.trim());
  if (c.length > 1) return "Multicolor";
  return COLORS.includes(c[0]) ? c[0] : "Red";
}
function typeOf(card) {
  const t = (card.type || card.category || "").toLowerCase();
  if (t.includes("leader")) return "Leader";
  if (t.includes("event")) return "Event";
  if (t.includes("stage")) return "Stage";
  return "Character";
}

async function main() {
  const out = [];
  const setMap = new Map();
  let page = 1;
  for (;;) {
    const url = `https://apitcg.com/api/one-piece/cards?page=${page}&limit=100`;
    const res = await fetch(url, { headers: { "x-api-key": KEY } });
    if (!res.ok) throw new Error(`apitcg ${res.status}`);
    const body = await res.json();
    const cards = body.data ?? body.cards ?? [];
    if (!cards.length) break;
    for (const card of cards) {
      const id = card.id || card.code; // e.g. OP01-001
      if (!id) continue;
      const setCode = String(id).split("-")[0].toUpperCase();
      const setName = card.set?.name || setCode;
      if (!setMap.has(setCode)) setMap.set(setCode, { name: setName, count: 0 });
      setMap.get(setCode).count++;
      const setPfx = String(id).split("-")[0];
      const img = `https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/one-piece/${setPfx}/${id}_EN.webp`;
      out.push({
        externalId: id,
        name: card.name,
        setCode,
        setName,
        releaseDate: card.set?.releaseDate || "2022/12/02",
        collectorNumber: id,
        number: String(id).split("-").pop() || "",
        domain: domainOf(card),
        type: typeOf(card),
        subtype: card.family || card.attribute?.name || null,
        rarity: card.rarity || "Common",
        hp: card.power ? parseInt(card.power, 10) || null : null,
        artist: null,
        flavorText: null,
        imageUrl: img,
        imageThumbUrl: img,
      });
    }
    console.log(`page ${page}: ${cards.length} cards (total ${out.length})`);
    if (cards.length < 100) break;
    page++;
  }
  console.log(`Built ${out.length} cards across ${setMap.size} sets.`);
  writeFileSync(join(process.cwd(), "prisma", "op-cards.json"), JSON.stringify(out));

  const sets = [...setMap.entries()].map(([code, v]) => ({
    code, name: v.name, slug: slugify(v.name) || code.toLowerCase(), series: "One Piece",
    releaseDate: "2022/12/02", total: v.count, logo: null, symbol: null,
  }));
  sets.sort((a, b) => a.code.localeCompare(b.code));
  const ts = `// AUTO-GENERATED by prisma/fetch-op.mjs from apitcg.com. Do not edit by hand.
export interface OnePieceSet { code: string; name: string; slug: string; series: string; releaseDate: string; total: number; logo: string | null; symbol: string | null; }
export const ONE_PIECE_SETS: OnePieceSet[] = ${JSON.stringify(sets)};
`;
  writeFileSync(join(process.cwd(), "src", "lib", "one-piece-sets.ts"), ts);
  console.log(`Wrote ${sets.length} sets.`);
}
main().catch((e) => { console.error(e); process.exit(1); });
